/// Flutter icons RPGIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RPGIcons
///      fonts:
///       - asset: fonts/RPGIcons.ttf
///
/// 
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
///
import 'package:flutter/widgets.dart';

class RPGIcons {
  RPGIcons._();

  static const _kFontFam = 'RPGIcons';
  static const String? _kFontPkg = null;

  static const IconData book = IconData(0xe93a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData broadsword = IconData(0xe946, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_six = IconData(0xe998, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scroll_unfurled = IconData(0xea8f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData two_dragons = IconData(0xead9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
